version: 2
jobs:

  build:
    docker:
      - image: circleci/python:3.7 # every job must define an image for the docker executor and subsequent jobs may define a different image.
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install
            sleep 60
      - run:
          command: |
            pipenv run python aws-locate.py
