version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: InstallTools
          command: apt-get update -y && apt-get install -y curl
      - run:
          name: DetectCloud
          command: bash run.sh
